# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class DMigrate < Formula
  desc "Framework fr datenbankunabhngige migrationen und datenverwaltung"
  homepage "https://github.com/pt9912/d-migrate"
  url "https://github.com/pt9912/d-migrate/releases/download/v0.5.0/d-migrate-0.5.0-homebrew.tar.gz"
  sha256 "0bc004aaebe89550e0d0a7ddeec5996613134e93b6605afc7d9efb0845d89647"
  license "MIT"

  depends_on "openjdk@21"

  def install
    release_dir = Dir["d-migrate-*"].fetch(0)
    libexec.install Dir["#{release_dir}/*"]
    (bin/"d-migrate").write_env_script(
      libexec/"bin/d-migrate",
      Language::Java.overridable_java_home_env("21"),
    )
  end

  test do
    assert_match "Database-agnostic migration", shell_output("#{bin}/d-migrate --help")
  end
end
