# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class DMigrate < Formula
  desc "Framework fr datenbankunabhngige migrationen und datenverwaltung"
  homepage "https://github.com/pt9912/d-migrate"
  url "https://github.com/pt9912/d-migrate/releases/download/v0.9.2/d-migrate-0.9.2-homebrew.tar.gz"
  sha256 "e5baa6a3dbc68a1fdfe14ef28da5f9726f0d0be85e17ccaab22116b80359649f"
  license "MIT"

  depends_on "openjdk@21"

  def install
    libexec.install Dir["*"]
    (bin/"d-migrate").write_env_script(
      libexec/"bin/d-migrate",
      Language::Java.overridable_java_home_env("21"),
    )
  end

  test do
    assert_match "Database-agnostic migration", shell_output("#{bin}/d-migrate --help")
  end
end
