# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class DMigrate < Formula
  desc "Database-agnostic schema migrations and data management as cli and mcp server (p"
  homepage "https://github.com/pt9912/d-migrate"
  url "https://github.com/pt9912/d-migrate/releases/download/v1.5.2/d-migrate-1.5.2-homebrew.tar.gz"
  sha256 "922bea48f16d0af016ab9bd4c410b0b7b39e13438b0ac837a61c812cef31aba0"
  license "MIT"

  depends_on "openjdk@21"

  def install
    libexec.install Dir["*"]
    (bin/"d-migrate").write_env_script(
      libexec/"bin/d-migrate",
      Language::Java.overridable_java_home_env("21"),
    )
  end

  test do
    assert_match "Database-agnostic migration", shell_output("#{bin}/d-migrate --help")
  end
end
